default: &default
    split_design_documents_per_view: true # optional
    default_language: :erlang # optional

development:
    <<: *default
    database: dev_whois
test:
    <<: *default
    database: test_whois
production:
    <<: *default
    database: <%= ENV['WHOIS'] %>