# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d9738ff51a8b9a694241ce6591bf5be9c39e6d457f5533eea25a25ff938141bc53f7d2e2eb6daa55b409c2c03c138bbab7330918d2bdaacd6848044a28a7673

test:
  secret_key_base: a6c77ea3cca19bb0dfd5d32a2d0917362d11402c7f882eef603e36028d6165438a71537284ac0ffba71950fa5f4d64c21edc740b024a06dbded0477c2e3527bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
